name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          exempt-issue-labels: 'help-wanted,keep'
          days-before-stale: 60
          days-before-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1
    permissions:
      issues: write